version: '3.9'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=heat-nlw-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - heat_nlw_data:/var/lib/postgres
volumes:
  heat_nlw_data: